service: football-v2-backend

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

plugins:
  - serverless-offline

functions:
  updateStandings:
    handler: src/standings/updateStandingsHandler.handler
    timeout: 30
    events:
      - http:
          path: standings
          method: post
          cors: true

  readStandings:
    handler: src/standings/readStandingsHandler.handler
    events:
      - http:
          path: standings/{league}/{season}
          method: get
          cors: true

  updateTopScorers:
    handler: src/top-scorers/updateTopScorersHandler.handler
    timeout: 30
    events:
      - http:
          path: topscorers
          method: post
          cors: true

  readTopScorers:
    handler: src/top-scorers/readTopScorersHandler.handler
    events:
      - http:
          path: topscorers/{league}/{season}
          method: get
          cors: true

  updateFixtures:
    handler: src/fixtures/updateFixturesHandler.handler
    timeout: 30
    events:
      - http:
          path: fixtures
          method: post
          cors: true

  readFixtures:
    handler: src/fixtures/readFixturesHandler.handler
    events:
      - http:
          path: fixtures/{league}/{season}/{option}
          method: get
          cors: true
