# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: football-v2-backend

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

plugins:
  - serverless-offline

# The `functions` block defines what code to deploy
functions:
  updateStandings:
    handler: src/standings/updateStandingsHandler.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: update-standings
          method: post
          cors: true
