service: football-v2-backend

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

plugins:
  - serverless-offline

functions:
  updateStandings:
    handler: src/standings/updateStandingsHandler.handler
    events:
      - http:
          path: standings
          method: post
          cors: true

  updateTopScorers:
    handler: src/top-scorers/updateTopScorersHandler.handler
    events:
      - http:
          path: topscorers
          method: post
          cors: true

  updateFixtures:
    handler: src/fixtures/updateFixturesHandler.handler
    events:
      - http:
          path: fixtures
          method: post
          cors: true
